### PR TITLE
Bug Fix: Profile not showing on website

### LINKED ISSUE #82: BUG: Profile not showing on website
## Description

- When visiting the website, its showing error in JS code. I have attach the screenshot for the same below. 
- I am working on solving this issue, please assign it to me.
- Because of this profile aren't loading

## Screenshot 

image

### PR DESCRIPTION
**Pull request by Alkaison**
## Fixes #82 

- Fix: syntax error in `profiles.json` file.
- Now all profiles are loading properly on website. 

## Screenshot

image

### CODE REVIEW

**Comment by Alkaison** [comment]
## Updates

- Along with the bug fix, I also added my Profile data into `profiles.json` with proper syntax.

**Review by pushkaraj2007 — CHANGES_REQUESTED** [review]
Looks good! 🔥

Thanks for contributing, just one request can you please create a seperate PR for adding your profile?

That way, we can seperate different PR for different tasks.

Just push a change of removing you profile from this PR and again create a seperate PR with adding your profile.

Thank you.

**Comment by Alkaison** [comment]
Hi @pushkaraj2007, done changes. I will create a new PR for profile addition.

Preview: https://techcreators-git-fork-alkaison-fixprofilesloading-pushkaraj.vercel.app/

**Review by pushkaraj2007 — APPROVED** [review]
Looks good! 🔥

Thank you for contributing. Don't forget to leave a star if you liked the project! ⭐

**Pull request merged**
