### PR TITLE
Add follow button and fix broken Image

### PR DESCRIPTION
**Pull request by devXprite**
### Preview:

https://user-images.githubusercontent.com/80192140/193486347-32e92b3c-911c-4a42-89a3-d00734357e2f.mp4

### CODE REVIEW

**Comment by devXprite** [comment]
> Looks great 🔥
> 
> Thanks for contributing, hope to see you again contributing on this repository 🚀

You're welcome @pushkaraj2007.

 I am participating in Hacktoberfest so can you please add **hacktoberfest-accepted** label to this pr

**Comment by pushkaraj2007** [comment]
Sure @devXprite 

BTW, this repo is not participating in hacktoberfest, so I don't know if this will count towards your hacktoberfest PRs.

**Comment by devXprite** [comment]
> Sure @devXprite
> 
> BTW, this repo is not participating in hacktoberfest, so I don't know if this will count towards your hacktoberfest PRs.

Thank @pushkaraj2007. 
This is my 4th PR for Hacktoberfest.

and If your PR labled as “HACKTOBERFEST-ACCEPTED" then it will count in hacktoberfest PRs.

**Comment by pushkaraj2007** [comment]
@devXprite, That's great

More power to you!!

**Pull request merged**
