### PR TITLE
added myprofile

### PR DESCRIPTION
**Pull request by dev-liza**
I have added my profile on TechCreators.
Please merge my PR..

### CODE REVIEW

**Comment by dev-liza** [comment]
solved the conflicting issues..

**Review by pushkaraj2007 — APPROVED** [review]
Looks good 🔥

Thanks for contributing, don't forget to leave a star if you liked the project ⭐

**Comment by dev-liza** [comment]
> Looks good 🔥
> 
> Thanks for contributing, don't forget to leave a star if you liked the project ⭐


Thanks for merging my PR!

**Comment by pushkaraj2007** [comment]
@dev-liza, You are welcome!

If you have any queries related to this project or want to connect with me, feel free to DM me on Twitter. 
My Twitter username is [@pushkaraj2007](https://twitter.com/pushkaraj2007) 🤝

**Comment by dev-liza** [comment]
Yup sure !!

**Pull request merged**
